version: '3'

services:

  users_structures_service:
    container_name: users_structures_service
    build: ./services/users_structures/
    volumes:
      - './services/users_structures:/usr/src/app'
      - './services/users_structures/package.json:/usr/src/package.json'
    ports:
      - '3000:3000' # expose ports - HOST:CONTAINER
    environment:
      - PORT=3000

  products_menus_service1:
    container_name: products_menus_service1
    build: ./services/products_menus/
    volumes:
      - './services/products_menus:/usr/src/app'
      - './services/products_menus/package.json:/usr/src/package.json'
    ports:
      - '3001:3001' # expose ports - HOST:CONTAINER
    environment:
      - PORT=3001


  products_menus_service2:
    container_name: products_menus_service2
    build: ./services/products_menus/
    volumes:
      - './services/products_menus:/usr/src/app'
      - './services/products_menus/package.json:/usr/src/package.json'
    ports:
      - '3002:3002' # expose ports - HOST:CONTAINER
    environment:
      - PORT=3002

  order_deliveries_service:
    container_name: order_deliveries_service
    build: ./services/order_deliveries/
    volumes:
      - './services/order_deliveries:/usr/src/app'
      - './services/order_deliveries/package.json:/usr/src/package.json'
    ports:
      - '3003:3003' # expose ports - HOST:CONTAINER
    environment:
      - PORT=3003


  notifications_service:
    container_name: notifications_service
    build: ./services/notifications/
    volumes:
      - './services/notifications:/usr/src/app'
      - './services/notifications/package.json:/usr/src/package.json'
    ports:
      - '3050:3050' # expose ports - HOST:CONTAINER
    environment:
      - PORT=3050

  swagger_service:
    container_name: swagger_service
    build: ./services/swagger/
    volumes:
      - './services/swagger:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '4000:4000' # expose ports - HOST:CONTAINER
    environment:
      - PORT=4000


      


  nginx:
    container_name: nginx-proxy
    build: ./nginx/
    ports:
      - '80:80' # expose ports - HOST:CONTAINER
    links:
      - swagger_service
      - users-service
      - products-service1
      - products-service2